version: '3.8'

services:
  discount-bot:
    build: .
    container_name: discount-bot
    volumes:
      - database:/bot/database
    restart: unless-stopped
    command: python3 bot.py

volumes:
  database: